services:
  - type: web
    name: telegram-straddle-bot
    env: python
    region: singapore
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: ADMIN_TELEGRAM_IDS
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.9
    healthCheckPath: /health
    autoDeploy: true
    
